name: peerTube_video_manager
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  river_player: ^0.1.4
  infinite_scroll_pagination: ^4.1.0
  cached_network_image:
  timeago:
  shimmer:
  url_launcher:

  peer_tube_api_sdk:
    git: git@github.com:RustLangLatam/peertube_api_sdk.git

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
